[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.9"
NODE_VERSION = "22"
TZ = "Europe/London"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"